n1 = input("Enter a first number: ")
n2 = input("Enter another number: ")
addition = float(n1) + float(n2)
print("Sum:", addition)
multiplication = float(n1) * float(n2)
print("Product:", multiplication)
subtraction = float(n1) - float(n2)
print("Difference:", subtraction)
division =float(n1) / float(n2)
print("Quotient:", division)
modulo =float(n1) % float(n2)
print("Rest:", modulo)
divisionRoundedWithoutDecimals =float(n1) / float(n2)
print("Division without Decimals: ", divisionRoundedWithoutDecimals)